// Step 2.1 — Generate two throwaway Arc Testnet wallets (owner + validator)
// and write their private keys to .env. Equivalent to running
// `cast wallet new --json` twice, without needing Foundry.
//
// Only addresses are printed. Private keys go straight into .env.
// TESTNET ONLY — never reuse these keys for real funds.
import { existsSync, writeFileSync } from "node:fs";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

const ENV_PATH = ".env";

if (existsSync(ENV_PATH) && !process.argv.includes("--force")) {
  console.error(
    `${ENV_PATH} already exists. Re-run with --force to overwrite it (existing keys will be lost).`,
  );
  process.exit(1);
}

const ownerKey = generatePrivateKey();
const validatorKey = generatePrivateKey();
const owner = privateKeyToAccount(ownerKey);
const validator = privateKeyToAccount(validatorKey);

const env = [
  "# Arc Testnet ERC-8004 quickstart — generated by generate-wallets.ts",
  "# TESTNET ONLY. Do not commit this file.",
  `OWNER_PRIVATE_KEY=${ownerKey}`,
  `VALIDATOR_PRIVATE_KEY=${validatorKey}`,
  "# METADATA_URI=ipfs://bafkreibdi6623n3xpf7ymk62ckb4bo75o3qemwkpfvp5i25j66itxvsoei",
  "",
].join("\n");

writeFileSync(ENV_PATH, env, { encoding: "utf8" });

console.log(`Wrote ${ENV_PATH} with two new wallets.\n`);
console.log(`Owner     (registers agent, requests validation): ${owner.address}`);
console.log(`Validator (records reputation, responds):        ${validator.address}`);
console.log("\nNext: fund BOTH addresses with Arc Testnet USDC at https://faucet.circle.com");
console.log("Then verify with: npm run balances");
